from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from .types import MarketContext, SourcePlan, market_dir_slug
from .sources import source_plan_sha256

# Every fleet-managed executor keeps its state under this root; the shared
# operator dir (master kill switch) is <GEO_DATA_ROOT>/operator.
GEO_DATA_ROOT = "data/geopolitics"

_HEADER = (
    "# GENERATED by the market-first discovery pipeline -- REVIEW BEFORE USE.\n"
    "# Generated from the durable market context (rule text pinned by SHA-256 at\n"
    "# context-build time; execution fails closed if Polymarket edits the rules).\n"
    "# The operator gate still applies: dry_run stays true and the position mode\n"
    "# stays alert_only until the standard inspect/preflight/ack sequence is run.\n"
)


def emit_bot_config(
    context: MarketContext,
    plan: SourcePlan,
    *,
    entry_usd: float,
    out_path: Path,
    ledger_path: str = "",
    dry_run: bool = True,
    entry_side: str = "YES",
    classifier_provider: str = "anthropic",
    classifier_model: str = "claude-sonnet-4-6",
    classifier_cli_binary: str = "claude",
    classifier_cli_timeout_seconds: int = 180,
    classifier_budget_db: str = "",
    classifier_max_escalations_per_hour: int = 4,
    classifier_max_escalations_per_day: int = 20,
    classifier_max_errors_per_hour: int = 3,
    central_feed_db: str = "",
    central_feed_stale_after_seconds: float = 60.0,
) -> Path:
    """Render a ready-to-review executor config for this market: the existing
    entry/defense/exit engines are the final execution component, so the
    pipeline's output is their input format. When `ledger_path` is given, the
    config binds the executor to the shared portfolio ledger so live fills
    debit the same budgets the pipeline allocates against."""
    if context.rule_analysis is None:
        raise ValueError(f"market {context.market_id} has no rule analysis; refusing to emit an executor config")
    if plan.rule_text_sha256 != context.rule_text_sha256:
        raise ValueError(f"source plan for {context.market_id} was built for a different rule-text version; rebuild it")
    if entry_side not in {"YES", "NO"}:
        raise ValueError(f"invalid entry_side {entry_side!r}")
    if context.kind == "grouped":
        # Location legs are YES-side instruments; a NO view on a leg is a YES
        # view on its siblings and belongs to the group-arbitrage report.
        payload = _location_config(
            context,
            plan,
            entry_usd,
            central_feed_db=central_feed_db,
            central_feed_stale_after_seconds=central_feed_stale_after_seconds,
        )
    else:
        payload = _binary_config(
            context,
            plan,
            entry_usd,
            entry_side,
            central_feed_db=central_feed_db,
            central_feed_stale_after_seconds=central_feed_stale_after_seconds,
        )
    # The executor inherits the pipeline's complete classification transport;
    # provider-only inheritance can pair Codex with a stale Claude model/binary.
    payload["classifier"]["provider"] = classifier_provider or "anthropic"
    payload["classifier"]["model"] = classifier_model
    payload["classifier"]["cli_binary"] = classifier_cli_binary
    payload["classifier"]["cli_timeout_seconds"] = int(
        classifier_cli_timeout_seconds
    )
    if classifier_provider.strip().lower() in {
        "codex_cli",
        "codex-cli",
        "codex",
    }:
        # There is no separate cheap-screen model configured for the Codex
        # transport. An empty value keeps screening disabled explicitly.
        payload["classifier"]["screen_model"] = ""
    if classifier_budget_db:
        payload["classifier"].update(
            {
                "budget_db_path": classifier_budget_db,
                "max_escalations_per_hour": int(classifier_max_escalations_per_hour),
                "max_escalations_per_day": int(classifier_max_escalations_per_day),
                "max_classifier_errors_per_hour": int(classifier_max_errors_per_hour),
            }
        )
    payload["execution"]["dry_run"] = dry_run
    if not dry_run:
        # Live confirmation is never allowed to inherit the cheaper paper
        # posture. The operator gate independently enforces the same invariant,
        # so a hand-edited or stale generated config also fails closed.
        payload["classifier"]["passes"] = max(2, int(payload["classifier"].get("passes", 1)))
        payload["classifier"]["require_pass_agreement"] = True
    if ledger_path:
        from .registry import region_of

        payload["portfolio"] = {
            "ledger_path": ledger_path,
            "market_id": context.market_id,
            "event_slug": context.event_slug,
            "correlation_group": context.correlation_group or "uncategorized",
            "region": region_of(context.rule_analysis.parties) if context.rule_analysis else "global",
            "deadline_iso": context.deadline_iso,
        }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(_HEADER + yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, width=100), encoding="utf-8")
    return out_path


def _binary_config(
    context: MarketContext,
    plan: SourcePlan,
    entry_usd: float,
    entry_side: str = "YES",
    *,
    central_feed_db: str = "",
    central_feed_stale_after_seconds: float = 60.0,
) -> dict[str, Any]:
    outcome = context.outcomes[0]
    return {
        "market": {
            "slug": context.event_slug,
            "question": outcome.question or context.question,
            "expected_question_contains": (outcome.question or context.question)[:60],
            "deadline_date": _date_only(context.deadline_iso),
            "held_side": "",
            "expected_rule_text_sha256": context.rule_text_sha256,
            "resolution_rules": context.rule_text,
        },
        "position": {
            "expected_yes_token_id": outcome.yes_token_id,
            "expected_no_token_id": outcome.no_token_id,
        },
        "entry": {"enabled": True, "side": entry_side, "usd_budget": entry_usd, "max_price": 0.90, "max_entries": 1},
        "classifier": {
            # claude_cli bills against the Claude subscription's weekly
            # limit; "anthropic" here silently routed every fleet bot to the
            # metered API (which has no credits and just errors).
            "provider": "claude_cli",
            "model": "claude-opus-4-8",
            # Cheap screen pass: the strong model only runs when this one sees
            # anything other than NO_ACTION.
            "screen_model": "claude-haiku-4-5-20251001",
            # Paper posture: one confirm pass. Two-pass agreement is a live
            # safety measure; operator review restores it when arming live.
            "passes": 1,
            "require_pass_agreement": False,
        },
        "execution": {
            "dry_run": True,
            "paper_fee_bps": 0.0,
            "paper_slippage_bps": 25.0,
            "paper_max_book_age_seconds": 10.0,
            "sell": {"enabled": True, "min_price": 0.03},
            "flip_buy": {"enabled": False},
        },
        "keywords": {"escalate_terms": plan.escalate_terms},
        "safety": {"one_shot": True, "max_executions": 2, "poll_seconds": 30.0, "armed_poll_seconds": 2.0},
        "sources": {
            **_sources_section(
                plan,
                central_feed_db=central_feed_db,
                central_feed_stale_after_seconds=central_feed_stale_after_seconds,
            ),
            # Binary fleet configs previously inherited Iran-specific default
            # terms and silently discarded other theaters before the keyword
            # gate. Source-plan terms are the correct per-market filter.
            "feed_include_terms": plan.escalate_terms,
        },
        "data_dir": f"{GEO_DATA_ROOT}/{_slug(context.market_id)}",
        "logs_dir": "logs",
    }


def _location_config(
    context: MarketContext,
    plan: SourcePlan,
    entry_usd: float,
    *,
    central_feed_db: str = "",
    central_feed_stale_after_seconds: float = 60.0,
) -> dict[str, Any]:
    return {
        "event": {
            "slug": context.event_slug,
            "question": context.question,
            "deadline_date": _date_only(context.deadline_iso),
            "held_location": "",
            "expected_rule_text_sha256": context.rule_text_sha256,
            "resolution_rules": context.rule_text,
        },
        "outcomes": [
            {
                "name": o.name,
                "label": o.label,
                "condition_id": o.condition_id,
                "yes_token_id": o.yes_token_id,
                "no_token_id": o.no_token_id,
                "rotation_target": False,
            }
            for o in context.outcomes
        ],
        "entry": {
            "enabled": True,
            # Every configured leg is enterable on a tier-one confirmation;
            # the operator should trim this list during review.
            "targets": [o.name for o in context.outcomes],
            "usd_budget": entry_usd,
            "max_price": 0.90,
            "max_entries": 1,
        },
        "classifier": {
            # claude_cli bills against the Claude subscription's weekly
            # limit; "anthropic" here silently routed every fleet bot to the
            # metered API (which has no credits and just errors).
            "provider": "claude_cli",
            "model": "claude-opus-4-8",
            # Cheap screen pass: the strong model only runs when this one sees
            # anything other than NO_ACTION.
            "screen_model": "claude-haiku-4-5-20251001",
            # Paper posture: one confirm pass. Two-pass agreement is a live
            # safety measure; operator review restores it when arming live.
            "passes": 1,
            "require_pass_agreement": False,
        },
        "execution": {
            "dry_run": True,
            "paper_fee_bps": 0.0,
            "paper_slippage_bps": 25.0,
            "paper_max_book_age_seconds": 10.0,
            "sell": {"enabled": True, "min_price": 0.03},
            "buy_rotation": {"enabled": False},
        },
        "safety": {"one_shot": True, "max_executions": 2, "poll_seconds": 30.0, "armed_poll_seconds": 2.0},
        "sources": {
            **_sources_section(
                plan,
                central_feed_db=central_feed_db,
                central_feed_stale_after_seconds=central_feed_stale_after_seconds,
            ),
            "feed_include_terms": plan.escalate_terms,
        },
        "data_dir": f"{GEO_DATA_ROOT}/{_slug(context.market_id)}",
        "logs_dir": "logs",
    }


def _sources_section(
    plan: SourcePlan,
    *,
    central_feed_db: str = "",
    central_feed_stale_after_seconds: float = 60.0,
) -> dict[str, Any]:
    payload = {
        "source_plan_sha256": source_plan_sha256(plan),
        "poll_urls": list(plan.poll_urls),
        "feed_urls": list(plan.feed_urls),
        "auto_trade_domains": list(plan.auto_trade_domains),
        "alert_only_domains": list(plan.alert_only_domains),
        "allow_feed_auto_trade": False,
        "max_trade_article_age_hours": 24.0,
        # Event-anchored depth capture: gate escalations, pre-order,
        # post-fill -> book_snapshots.jsonl (the slippage/repricing dataset).
        "log_book_snapshots": True,
    }
    if central_feed_db:
        payload["central_feed_db"] = central_feed_db
        payload["central_feed_stale_after_seconds"] = central_feed_stale_after_seconds
    return payload


def _date_only(deadline_iso: str) -> str:
    return (deadline_iso or "").strip()[:10]


def _slug(market_id: str) -> str:
    return market_dir_slug(market_id)
